### ISSUE TITLE
No webdrivers when you change compass data path

### ISSUE THREAD

**Issue by lucastucious** [DSPaul/COMPASS#60] opened 2023-10-27 22:13 UTC
**Describe the bug**
After changing path for Compass data, webdrivers can't download .

So I cannot download homebrewery cover, for example 

**To Reproduce**
1. Change data path, maybe on another hard drive
2. Relaunch
3. See the error message "chrome webdriver could not be initialised"

**Screenshots/files**
![Screenshot_2023-10-28-00-00-52-63_fc90557b4939f0bdf6f556efb0a965c9.jpg](https://github.com/DSPaul/COMPASS/assets/28046122/ef26b210-1095-48cd-a2a7-69b7256a793c)

**System info (please complete the following information):**
 - OS: Windows 10
 - latest version 1.15

**Comment by DSPaul** [comment] 2023-10-28 09:16
I looked into it. I think the changed data path is a red herring, I tried it myself and it works fine, everything in the code also looks good on that front. 

The error you get however can only occur when COMPASS detects that you have chrome installed but you said that you don't so the issue is most likely related to that. So I have taken the following steps to mitigate this issue:
- COMPASS would only fall back to firefox and then edge if chrome was not installed, but not if it thought it was installed and then failed. I have changed this so that it will also fall back to the next browser in line if initialisation fails. 
- That however doesn't address the core issue that a chrome install is wrongfully detected so I have expanded the check to see  if a program is installed to be more thorough to avoid false positives.

**Comment by lucastucious** [comment] 2023-10-29 12:57
After manys verifications :
- I don't use Chrome, but Vivaldi, a Chromium-based browser
- After talking about this issue here and on discord, i've found that a was having Chrome installed... but obvisously an outdated version. 
- So i make the chrome update, but i still have the error !

**Comment by lucastucious** [comment] 2023-10-29 13:02
Here is an error, i think related to this issue, when i try to renew cover from an homebrewery item : 
![image](https://github.com/DSPaul/COMPASS/assets/28046122/e091916e-8c32-462c-8572-f665a8ea005c)

and here is the log
[all.log](https://github.com/DSPaul/COMPASS/files/13198133/all.log)

**Comment by lucastucious** [comment] 2023-10-30 20:09
Here is what i found : 
- Chrome is installed at `C:\Program Files\Google\Chrome\Application\chrome.exe`
- I used to have chromium, but not anymore (before Compass installation)
- i have a chromium.exe located in `C:\Users\lucas\AppData\Local\JxBrowser\7.27`, but it's for flutter development
- Vivaldi (chromium based) is located here : `C:\Users\lucas\AppData\Local\Vivaldi\Application`

the log from F:/COMPASS is here [all.log](https://github.com/DSPaul/COMPASS/files/13209470/all.log)

**Comment by DSPaul** [comment] 2023-10-30 22:47
> Windows still think i have chromium, but when i want to uninstall it, it cant find the exe

Seems like windows has exactly the same problem COMPASS has, something must have gone wrong while uninstalling so the files are deleted but there is still a registry entry in windows indicating that the program is still there, not much I can do about it. But with the new code it will now just move on from this problem and use firefox so all good. 

I have also solved the crash, it was trying to take the most recent webdriver but because you didn't have a webdriver due to your problem, it was trying to take the last out of an empty list, hence the error "sequence contains no elements".

**Comment by lucastucious** [comment] 2023-10-31 08:21
Still, why compass can't find the chrome folder ?

Le lun. 30 oct. 2023, 23:47, Paul De Smul ***@***.***> a
écrit :

**Comment by DSPaul** [comment] 2023-10-31 08:41
It doesn't search for it, that would take way too long. Imagine if COMPASS was running on a PC with 16TB hard drive full of data, good luck finding that one chrome.exe file. 

So instead of doing that, it looks at the windows registry where windows keeps a table of installed programs and where they are installed. It's the same list windows uses when you go to Apps in the windows settings or when you search for apps using Windows search. It's specifically designed so that you don't have to hunt down the right exe file every time you want to start an app.

**Comment by lucastucious** [comment] 2023-10-31 09:15
I understand, but since I have a registry entry for chromium, chrome and
Firefox, you could have fallback when the first isn't found

**Comment by DSPaul** [comment] 2023-10-31 10:02
That is exactly what I have done in the first commit that references this issue, the fix will be part of the next update.

**Comment by lucastucious** [comment] 2023-10-31 10:03
More info :
I've COMPASS installed on another computer. No data path changed, but still this message. here is the log [all.log](https://github.com/DSPaul/COMPASS/files/13214862/all.log)

**Comment by DSPaul** [comment] 2023-10-31 20:25
Looked at the log and despite it being the same error, the problem is different. 

In this case it does detect your chrome install correctly but fails to download the webdriver itself. 
Seems like chrome changed download url for their webdrivers starting with with version 115 so if you have an up to date version of chrome (118 at the time of writing) it will indeed fail.

The package I use (WebDriverManager.NET) has released a update that fixes this which will be included in the next release of COMPASS.

**Closed** 2023-11-07 19:16 UTC
Labels: bug
